[Taichi] version 1.7.2, llvm 15.0.4, commit 0131dce9, linux, python 3.11.10
[Taichi] Starting on arch=cuda
0.0001
Traceback (most recent call last):
  File "/home/bgailleton/Desktop/code/fastflow_taichi/example_fill_topo.py", line 17, in <module>
    ff.flow.topofill(router)
  File "/home/bgailleton/Desktop/code/fastflow_taichi/fastflow_taichi/flow/fill_topo.py", line 34, in topofill
    _topofill(flow_field.z, flow_field.z_, flow_field.z__, flow_field.receivers_, flow_field.receivers__, epsilon, it+1)
  File "/home/bgailleton/miniforge3/envs/scb/lib/python3.11/site-packages/taichi/lang/kernel_impl.py", line 1117, in wrapped
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiNameError: 
File "/home/bgailleton/Desktop/code/fastflow_taichi/fastflow_taichi/flow/fill_topo.py", line 9, in _topofill:
        if(i == rec_[i] or z[i]>z_[rec_[i]] or rec_[i] == rec_[rec_i] and
                                                               ^^^^^
Name "rec_i" is not defined
